### ISSUE TITLE
Receive dash remain open after reception

### ISSUE THREAD

**Issue by margori** [dashpay/dash-wallet#198]
I have two phones.
* Using version 6.4.1 testnet in phone 1.
* Tap in receive dash button
* Set any amount of fiat money
* With phone 2  using wallt dash 6.4.1 testnet, scan QR
* Send dashes.

Expected
* the "receive dash" page in phone 1 to be closed when dashes are received.

Actual 
* the "receive dash" page in phone 1 remains open when dashes are received.

**Comment by HashEngineering** [comment]
We haven't looked into this issue yet.  We may consider it for our redesigned interface.

**Comment by HashEngineering** [comment]
This will be closed as it has been 4 years.  Let us know if this is a problem with version 9.x.
