### ISSUE TITLE
Empty wallet feature includes unconfirmed balance that can't be sent

### ISSUE THREAD

**Issue by agulab** [dashpay/dash-wallet#216]
I'm on version 6.4.5 but also found this bug on previous versions:
On SEND screen, using the EMPTY WALLET feature puts an amount in AMOUNT TO PAY that includes unconfirmed balance. So I see a transaction that will include all my funds.
I send it, and the resulting transaction that is created only includes the confirmed balance.
I'm pretty sure the unconfirmed balance CAN'T be sent, so it shouldn't be included when clicking EMPTY WALLET because that makes the user think it is creating a transaction for an amount that is different to the actual amount finally sent.

Thanks for your work!

**Comment by HashEngineering** [comment]
Thanks for pointing out this bug.  Actually, with Dash Wallet we do allow sending 0-conf transactions, transactions that are not confirmed because it is supported by the Dash Network.

**Comment by HashEngineering** [comment]
This will be closed because it has been 4 years.  Let us know if this is still an issue with version 9.x of the app.
