### ISSUE TITLE
Is it possible to make xpub available again?

### ISSUE THREAD

**Issue by eloyesp** [dashpay/dash-wallet#639]
It seems that there is no way to get access to the master public key (xpub) in the current interface, as far as I understand, it was removed in #166 (specifically on commit: 55232256e0e91d44d825a476589d3274ca7d529b) because:

> It was not possible to call ExtendedPublicKeyFragment.show without significant refactoring

I wanted to know if that is still an issue or if making the xpub accessible for the user could be addressed. As you know that could be used by other systems to make it possible to receive payments without reusing addresses and without sharing private keys.

## Expected Behavior

I would like to make it possible to view (as alpha and qr), and share the xpub, that is currently unavailable.

**Comment by HashEngineering** [comment]
Yes, it is possible, but it is not on the list of priorities.

**Comment by HashEngineering** [comment]
This feature was added back in More / Tools / Extended Public Key in v7.4.8

![image](https://github.com/dashpay/dash-wallet/assets/5956129/1eca7d6b-a5ff-4f52-b7ad-a48acdc151ab)
![image](https://github.com/dashpay/dash-wallet/assets/5956129/cb30003c-f9d9-45ed-bbf4-c4b7fdeb71d9)
