### ISSUE TITLE
android:tint specified in <shape>

### ISSUE THREAD

**Issue by john2020star** [dashpay/dash-wallet#648]
I found that you specified android:tint in <shape> of the file progress_horizontal.xml, which is not supported at API Level 21. It can cause the color of the drawable displaying inconsistently. Avoid using it.

**Comment by HashEngineering** [comment]
There are some other places where this will need to be fixed as well.

**Comment by HashEngineering** [comment]
Android SDK 21 is no longer supported.  The current min SDK is 23 (Android 6).
