### ISSUE TITLE
Crash on start on version v7.3.1

### ISSUE THREAD

**Issue by eloyesp** [dashpay/dash-wallet#708]
I've just updated the application from f-droid and I crash after showing the loading screen. After some tries, a popup offer send a crash report, but it also fails.

I've also tried to downgrade to version 7.0.9 (the last release on f-droid, that I were using) and it fails with an: "unknown error".

I'm currently using HavocOS without Google Play Services.

**Comment by eloyesp** [comment]
I've checked reinstalling (cleanly) and it crash. I've reinstalled the old version again and it works.

**Comment by HashEngineering** [comment]
A fix has been released on the repo that will be picked up by F-droid.

https://github.com/HashEngineeringSolutions/dash-wallet/releases/tag/v7.3.2-foss
