### ISSUE TITLE
Splash screen only.

### ISSUE THREAD

**Issue by anarchotaoist** [dashpay/dash-wallet#758]
Cannot open wallet on Android. It is stuck at the splash screen. No login option.

## Expected Behavior
App opens up to login - the logs in.

## Current Behavior
Opens to splash screen with no login option.

* Operating System and version (desktop, server, or mobile): Android - F-Droid version 7.3.2

**Comment by anarchotaoist** [comment]
I suspect it may have something to do where the data is stored. I have the same issue with Bitwarden app also, in that after every system update then both apps will not open.
After clearing cache/storage then apps will open. This of course if very annoying for the Dash wallet as you then have to restore and re-download the blockchain again.

**Comment by HashEngineering** [comment]
Was this issue resolved?  On F-Droid version 8.1.3 was published.

**Comment by HashEngineering** [comment]
This will be closed since 7.3.2 is no longer supported.
