### ISSUE TITLE
Missing documentation on the seed format for manual recovery

### ISSUE THREAD

**Issue by eloyesp** [dashpay/dash-wallet#759]
On the README file, it is mentioned that a seed phrase (mnemonic) can be used for backup, but there is no way to know if the mnemonic match BIP39 or not (and I'm almost sure that it doesn't). Also, on the [README.recovery.md][recovery] file, there is no mention about the mnemonic.

So, if mnemonic uses BIP39, I can do a PR adding a mention on the readme, if the format is not compatible, it would be nice to explain the recovery process out of the app on the recovery file.

Regards.

[recovery]: https://github.com/dashevo/dash-wallet/blob/28954b3043ced3f4698813dca65c52f8bb4648b2/wallet/README.recover.md

**Comment by HashEngineering** [comment]
This app does use BIP39 as the spec for mnemonic phrases.

**Comment by HashEngineering** [comment]
README.recovery.md explains how to recover coins from backup files made by previous versions of Dash Wallet, without using Dash Wallet.

It is correct that it doesn't explain how to recover coins from the recovery phrase in other software.  This particular recovery document should be updated.
